name: Mirroring

on: [push, delete]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:                                              
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            gitlab.opencode.de:tm-test/sync-test.git
          ssh_private_key:                              # <-- use 'secrets' to pass credential information.
            ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
